const books = [
  {
    "author": "Chinua Achebe",
    "country": "Nigeria",
    "category":"fiction",
    "imageLink": "images/things-fall-apart.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
    "pages": 209,
    "title": "Things Fall Apart",
    "year": 1958,
    "price":95,
    "ISBN":"978-0-545-01022-1"
  },
  {
    "author": "Hans Christian Andersen",
    "country": "Denmark",
    "category":"science",
    "imageLink": "images/fairy-tales.jpg",
    "language": "Danish",
    "link": "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
    "pages": 784,
    "title": "Fairy tales",
    "year": 1836,
    "price":95,
    "ISBN":"978-0-545-01022-2"
  },
  {
    "author": "Dante Alighieri",
    "country": "Italy",
    "category":"Art",
    "imageLink": "images/the-divine-comedy.jpg",
    "language": "Italian",
    "link": "https://en.wikipedia.org/wiki/Divine_Comedy\n",
    "pages": 928,
    "title": "The Divine Comedy",
    "year": 1315,
    "price":95,
    "ISBN":"978-0-545-01022-3"
  },
  {
    "author": "Unknown",
    "country": "Sumer and Akkadian Empire",
    "category":"fiction",
    "imageLink": "images/the-epic-of-gilgamesh.jpg",
    "language": "Akkadian",
    "link": "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n",
    "pages": 160,
    "title": "The Epic Of Gilgamesh",
    "year": -1700,
    "price":100,
    "ISBN":"978-0-545-01022-4"
  },
  {
    "author": "Unknown",
    "country": "Achaemenid Empire",
    "category":"Tec",
    "imageLink": "images/the-book-of-job.jpg",
    "language": "Hebrew",
    "link": "https://en.wikipedia.org/wiki/Book_of_Job\n",
    "pages": 176,
    "title": "The Book Of Job",
    "year": -600,
    "price":100,
    "ISBN":"978-0-545-01022-5"
  },
  {
    "author": "Unknown",
    "country": "India/Iran/Iraq/Egypt/Tajikistan",
    "category":"fiction",
    "imageLink": "images/one-thousand-and-one-nights.jpg",
    "language": "Arabic",
    "link": "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
    "pages": 288,
    "title": "One Thousand and One Nights",
    "year": 1200,
    "price":100,
    "ISBN":"978-0-545-01022-6"
  },
  {
    "author": "Unknown",
    "country": "Iceland",
    "category":"science",
    "imageLink": "images/njals-saga.jpg",
    "language": "Old Norse",
    "link": "https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga\n",
    "pages": 384,
    "title": "Nj\u00e1l's Saga",
    "year": 1350,
    "price":100,
    "ISBN":"978-0-545-01022-7"
  },
  {
    "author": "Jane Austen",
    "country": "United Kingdom",
    "category":"Art",
    "imageLink": "images/pride-and-prejudice.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
    "pages": 226,
    "title": "Pride and Prejudice",
    "year": 1813,
    "price":120,
    "ISBN":"978-0-545-01022-8"
  },
  {
    "author": "Honor\u00e9 de Balzac",
    "country": "France",
    "category":"History",
    "imageLink": "images/le-pere-goriot.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot\n",
    "pages": 443,
    "title": "Le P\u00e8re Goriot",
    "year": 1835,
    "price":120,
    "ISBN":"978-0-545-01022-20"
  },
  {
    "author": "Samuel Beckett",
    "country": "Republic of Ireland",
    "category":"History",
    "imageLink": "images/molloy-malone-dies-the-unnamable.jpg",
    "language": "French, English",
    "link": "https://en.wikipedia.org/wiki/Molloy_(novel)\n",
    "pages": 256,
    "title": "Molloy, Malone Dies, The Unnamable, the trilogy",
    "year": 1952,
    "price": 80,
    "ISBN":"978-0-545-01022-9"
  },
  {
    "author": "Jorge Luis Borges",
    "country": "Argentina",
    "category":"History",
    "imageLink": "images/ficciones.jpg",
    "language": "Spanish",
    "link": "https://en.wikipedia.org/wiki/Ficciones\n",
    "pages": 224,
    "title": "Ficciones",
    "year": 1965,
    "price": 100,
    "ISBN":"978-0-545-01022-10"
  },
  {
    "author": "Emily Bront\u00eb",
    "country": "United Kingdom",
    "category":"fiction",
    "imageLink": "images/wuthering-heights.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Wuthering_Heights\n",
    "pages": 342,
    "title": "Wuthering Heights",
    "year": 1847,
    "price":120,
    "ISBN":"978-0-545-01022-11"
  },
  {
    "author": "Albert Camus",
    "country": "Algeria, French Empire",
    "category":"History",
    "imageLink": "images/l-etranger.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/The_Stranger_(novel)\n",
    "pages": 185,
    "title": "The Stranger",
    "year": 1942,
    "price":120,
    "ISBN":"978-0-545-01022-12"
  },
  {
    "author": "Paul Celan",
    "country": "Romania, France",
    "category":"Art",
    "imageLink": "images/poems-paul-celan.jpg",
    "language": "German",
    "link": "\n",
    "pages": 320,
    "title": "Poems",
    "year": 1952,
    "price":120,
    "ISBN":"978-0-545-01022-13"
  },
  {
    "author": "Louis-Ferdinand C\u00e9line",
    "country": "France",
    "category":"medicine",
    "imageLink": "images/voyage-au-bout-de-la-nuit.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night\n",
    "pages": 505,
    "title": "Journey to the End of the Night",
    "year": 1932,
    "price":120,
    "ISBN":"978-0-545-01022-14"
  },
  {
    "author": "Miguel de Cervantes",
    "country": "Spain",
    "category":"medicine",
    "imageLink": "images/don-quijote-de-la-mancha.jpg",
    "language": "Spanish",
    "link": "https://en.wikipedia.org/wiki/Don_Quixote\n",
    "pages": 1056,
    "title": "Don Quijote De La Mancha",
    "year": 1610,
    "price":120,
    "ISBN":"978-0-545-01022-15"
  },
  {
    "author": "Geoffrey Chaucer",
    "country": "England",
    "category":"medicine",
    "imageLink": "images/the-canterbury-tales.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/The_Canterbury_Tales\n",
    "pages": 544,
    "title": "The Canterbury Tales",
    "year": 1450,
    "price":120,
    "ISBN":"978-0-545-01022-16"
  },
  {
    "author": "Anton Chekhov",
    "country": "Russia",
    "category":"medicine",
    "imageLink": "images/stories-of-anton-chekhov.jpg",
    "language": "Russian",
    "link": "https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov\n",
    "pages": 194,
    "title": "Stories",
    "year": 1886,
    "price":120,
    "ISBN":"978-0-545-01022-17"
  },
  {
    "author": "Joseph Conrad",
    "country": "United Kingdom",
    "category":"Story",
    "imageLink": "images/nostromo.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Nostromo\n",
    "pages": 320,
    "title": "Nostromo",
    "year": 1904,
    "price":120,
    "ISBN":"978-0-545-01022-18"
  },
  {
    "author": "Charles Dickens",
    "country": "United Kingdom",
    "category":"Story",
    "imageLink": "images/great-expectations.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Great_Expectations\n",
    "pages": 194,
    "title": "Great Expectations",
    "year": 1861,
    "price":120,
    "ISBN":"978-0-545-01022-19"
  }
]